---
title: "`Rmarkdown` in `PockeR`: an example"
author: "Lino Galiana"
date: "`r format(Sys.Date(), format = '%d %B %Y')` "
output:
  html_document:
    css: ./style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This `markdown` is used to test if `Python` works in `PockeR` repository. It is automatically built using continuous integration. 

This `markdown` is also the occasion to compare `Rcpp`, `Python` and `R` speed on the same program, a cumulative sum. I use, in the three cases, loops even if I know it is inefficient.


# Python



```{python, eval = TRUE}
import numpy as np
import datetime
import statistics

def cumsum_py(n = 1000): 
  start = datetime.datetime.now()
  x = np.random.uniform(0,1,n)
  for i in range(1,n):
    x[i] += x[i-1]
  end = datetime.datetime.now()
  c = end - start
  return(c.microseconds/1000)

exec_time_python = [cumsum_py(100000) for k in range(100)]

print("Time for a cumulative sum over a vector of size 1000 (milliseconds):")
print(statistics.median(exec_time_python))

```

# `R`

```{r}

cumsum_R <- function(n = 1000){
  start <- Sys.time()
  x = runif(n)
  for (i in seq(from = 3, to = n)){
    x[i] <- x[i] + x[i-1]
  }
  end <- Sys.time()
  c <- as.numeric(difftime(end, start, units="secs"))
  return(c*1000)
}

exec_time_R = replicate(100, cumsum_R(100000))

print("Time for a cumulative sum over a vector of size 1000 (milliseconds):")
print(median(exec_time_R))

```

# `Rcpp`

```{Rcpp, eval = FALSE}
#include <Rcpp.h>
#include <Rcpp/Benchmark/Timer.h>

using namespace Rcpp;

// [[Rcpp::export]]
double cumsum_cpp(int n) {
  
  // start the timer
  Timer timer;
  timer.step("start");        // record the starting point
  
  NumericVector x = runif(n);
  
  for (int i = 1 ; i < x.length() ; i++){
    x[i] += x[i-1];
  }
  
  timer.step("end");   // record the final step    
  
  
  NumericVector res(timer);   // 
  for (int i=0; i<res.size(); i++) {
    res[i] = res[i] / n;
  }
  return (res[1]-res[0])/1000; // Milliseconds    
  
}
```

```{r, echo = FALSE}
Rcpp::sourceCpp("simple_rcpp.cpp")
```


```{r}
exec_time_cpp = replicate(100, cumsum_cpp(100000))

print("Time for a cumulative sum over a vector of size 1000 (milliseconds):")
print(median(exec_time_cpp))

```

